server:
  port: 8087

#数据库配置
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/blog
  jpa:
    show-sql: true
#redis配置
  redis:
    host: 101.200.61.210
    database: 0
    port: 6379
    password: hxl#101095
    jedis:
      pool:
        min-idle: 0
        max-idle: 8
        max-active: 8
        max-wait: -1ms
    timeout: 3000ms






